### ISSUE TITLE
Please verify the bot

### ISSUE THREAD

**Issue by Infernotex** [Namchee/pleasantcord#81]
I would love to add the bot to my server, but I am unable to since the bot isn't verified. pls fix

**Comment by Infernotex** [comment]
![image](https://user-images.githubusercontent.com/89591187/188334537-84d8bf47-c7b9-4d09-8c09-a4e49df972ae.png)

**Comment by Namchee** [comment]
Thanks for submitting an issue.

Apologies due to my lack of time to maintain the bot. I've submitted the application, but I'm missing some requirements. Please wait until Wednesday and I'll close this issue once the intent has been approved.
